/*
 * Copyright (C) Ascensio System SIA 2012-2019. All rights reserved
 *
 * https://www.onlyoffice.com/
 *
 * Version: 5.3.4 (build:3)
 */

(function(f,e){function Oa(e){return Vc.locateFile?Vc.locateFile(e,Fe):Fe+e}function eb(e){var f=Yd[ne>>2];e=f+e+15&-16;if(e<=zb)Yd[ne>>2]=e;else if(!tc(e))return 0;return f}function db(e,f,w){var Pa=f+w;for(w=f;e[w]&&!(w>=Pa);)++w;if(16<w-f&&e.subarray&&ze)return ze.decode(e.subarray(f,w));for(Pa="";f<w;){var Ja=e[f++];if(Ja&128){var Da=e[f++]&63;if(192==(Ja&224))Pa+=String.fromCharCode((Ja&31)<<6|Da);else{var Ha=e[f++]&63;Ja=224==(Ja&240)?(Ja&15)<<12|Da<<6|Ha:(Ja&7)<<18|Da<<12|Ha<<6|e[f++]&63;65536>
Ja?Pa+=String.fromCharCode(Ja):(Ja-=65536,Pa+=String.fromCharCode(55296|Ja>>10,56320|Ja&1023))}}else Pa+=String.fromCharCode(Ja)}return Pa}function Za(e,f){0<e%f&&(e+=f-e%f);return e}function Ha(){Vc.HEAP8=lb=new Int8Array(Zf);Vc.HEAP16=new Int16Array(Zf);Vc.HEAP32=Yd=new Int32Array(Zf);Vc.HEAPU8=ic=new Uint8Array(Zf);Vc.HEAPU16=new Uint16Array(Zf);Vc.HEAPU32=new Uint32Array(Zf);Vc.HEAPF32=new Float32Array(Zf);Vc.HEAPF64=new Float64Array(Zf)}function Da(f){for(;0<f.length;){var w=f.shift();if("function"==
typeof w)w();else{var Pa=w.func;"number"===typeof Pa?w.CFf===e?Vc.dynCall_v(Pa):Vc.dynCall_vi(Pa,w.CFf):Pa(w.CFf===e?null:w.CFf)}}}function Qb(e){return String.prototype.startsWith?e.startsWith("data:application/octet-stream;base64,"):0===e.indexOf("data:application/octet-stream;base64,")}function Ra(){try{if(Vc.wasmBinary)return new Uint8Array(Vc.wasmBinary);if(Vc.readBinary)return Vc.readBinary(Le);throw"both async and sync fetching of the wasm failed";}catch(Pa){Ja(Pa)}}function ac(){return Vc.wasmBinary||
!rf&&!hf||"function"!==typeof te?new Promise(function(e){e(Ra())}):te(Le,{credentials:"same-origin"}).then(function(e){if(!e.ok)throw"failed to load wasm binary file at '"+Le+"'";return e.arrayBuffer()}).catch(function(){return Ra()})}function Ya(e){function f(e){Vc.asm=e.exports;vb--;Vc.monitorRunDependencies&&Vc.monitorRunDependencies(vb);0==vb&&(null!==sd&&(clearInterval(sd),sd=null),jd&&(e=jd,jd=null,e()))}function w(e){f(e.instance)}function Pa(e){ff().then(function(e){return WebAssembly.instantiate(e,
Da)}).then(e,function(e){Hg("failed to asynchronously prepare wasm: "+e);Ja(e)})}var Da={env:e,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:Rg};vb++;Vc.monitorRunDependencies&&Vc.monitorRunDependencies(vb);if(Vc.instantiateWasm)try{return Vc.instantiateWasm(Da,f)}catch(dj){return Hg("Module.instantiateWasm callback failed with error: "+dj),!1}Vc.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Qb(Le)||"function"!==typeof te?Pa(w):WebAssembly.instantiateStreaming(te(Le,
{credentials:"same-origin"}),Da).then(w,function(e){Hg("wasm streaming compile failed: "+e);Hg("falling back to ArrayBuffer instantiation");Pa(w)});return{}}function bb(e){if(bb.Cxg){var f=Yd[e>>2];var w=Yd[f>>2]}else bb.Cxg=!0,gd.USER=gd.LOGNAME="web_user",gd.PATH="/",gd.PWD="/",gd.HOME="/home/web_user",gd.LANG="C.UTF-8",gd._=Vc.thisProgram,w=nh?re(1024):eb(1024),f=nh?re(256):eb(256),Yd[f>>2]=w,Yd[e>>2]=f;e=[];var Pa=0,Ja;for(Ja in gd)if("string"===typeof gd[Ja]){var Da=Ja+"="+gd[Ja];e.push(Da);
Pa+=Da.length}if(1024<Pa)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(Ja=0;Ja<e.length;Ja++){Pa=Da=e[Ja];for(var Ha=w,Xa=0;Xa<Pa.length;++Xa)lb[Ha++>>0]=Pa.charCodeAt(Xa);lb[Ha>>0]=0;Yd[f+4*Ja>>2]=w;w+=Da.length+1}Yd[f+4*e.length>>2]=0}function me(e,f){Pc(e,f||1);throw"longjmp";}function tc(e){if(2147418112<e)return!1;for(var f=Math.max(zb,16777216);f<e;)f=536870912>=f?Za(2*f,65536):Math.min(Za((3*f+2147483648)/4,65536),2147418112);e=Za(f,65536);var w=Vc.buffer.byteLength;try{var Pa=
-1!==Fh.grow((e-w)/65536)?Vc.buffer=Fh.buffer:null}catch(Nd){Pa=null}if(!Pa||Pa.byteLength!=f)return!1;Vc.buffer=Zf=Pa;Ha();zb=f;return!0}function ec(e){if(0===e)return 0;e=e?db(ic,e,void 0):"";if(!gd.hasOwnProperty(e))return 0;ec.NSf&&Zc(ec.NSf);e=gd[e];for(var f=0,w=0;w<e.length;++w){var Pa=e.charCodeAt(w);55296<=Pa&&57343>=Pa&&(Pa=65536+((Pa&1023)<<10)|e.charCodeAt(++w)&1023);127>=Pa?++f:f=2047>=Pa?f+2:65535>=Pa?f+3:f+4}var Ja=f+1;if(f=re(Ja))if(w=lb,Pa=f,0<Ja){Ja=Pa+Ja-1;for(var Da=0;Da<e.length;++Da){var Ha=
e.charCodeAt(Da);if(55296<=Ha&&57343>=Ha){var Xa=e.charCodeAt(++Da);Ha=65536+((Ha&1023)<<10)|Xa&1023}if(127>=Ha){if(Pa>=Ja)break;w[Pa++]=Ha}else{if(2047>=Ha){if(Pa+1>=Ja)break;w[Pa++]=192|Ha>>6}else{if(65535>=Ha){if(Pa+2>=Ja)break;w[Pa++]=224|Ha>>12}else{if(Pa+3>=Ja)break;w[Pa++]=240|Ha>>18;w[Pa++]=128|Ha>>12&63}w[Pa++]=128|Ha>>6&63}w[Pa++]=128|Ha&63}}w[Pa]=0}ec.NSf=f;return ec.NSf}function xc(e){this.name="ExitStatus";this.message="Program terminated with exit("+e+")";this.status=e}function nc(){function e(){if(!Vc.calledRun&&
(Vc.calledRun=!0,!wd)){nh||(nh=!0,Da(ej));Da(Tg);if(Vc.onRuntimeInitialized)Vc.onRuntimeInitialized();if(Vc.postRun)for("function"==typeof Vc.postRun&&(Vc.postRun=[Vc.postRun]);Vc.postRun.length;)Ub.unshift(Vc.postRun.shift());Da(Ub)}}if(!(0<vb)){if(Vc.preRun)for("function"==typeof Vc.preRun&&(Vc.preRun=[Vc.preRun]);Vc.preRun.length;)Gf.unshift(Vc.preRun.shift());Da(Gf);0<vb||Vc.calledRun||(Vc.setStatus?(Vc.setStatus("Running..."),setTimeout(function(){setTimeout(function(){Vc.setStatus("")},1);e()},
1)):e())}}function Ja(f){if(Vc.onAbort)Vc.onAbort(f);f!==e?(We(f),Hg(f),f=JSON.stringify(f)):f="";wd=!0;throw"abort("+f+"). Build with -s ASSERTIONS=1 for more info.";}function Xa(){this.yNd=this.pFc=this.iYb=this.fK=this.vwc=this.mY=this.height=this.TX=this.B3=this.tNa=0;this.PAa=this.P2="";this.w$f=this.x$f=this.Ydg=this.$dg=this.Zdg=this.UQf=this.TQf=this.aeg=this.WQf=this.VQf=this.Xdg=this.beg=this.Ksf=0;this.esf=[]}function mf(){this.AEc=this.dvc=this.YAa=this.mCa=this.iia=this.goa=this.Era=
this.Mia=this.height=this.width=this.X5f=this.V5f=this.Y5f=this.W5f=0}function ub(){this.mode=this.pitch=this.rows=this.width=this.top=this.left=0}var kd=f.AscFonts,te=f.fetch,ff=null;f.AscDesktopEditor&&document.currentScript&&0==document.currentScript.src.indexOf("file:///")?(te=e,ff=function(){var e="ascdesktop://fonts/"+Le.substr(8);return new Promise(function(f){var w=new XMLHttpRequest;w.open("GET",e,!0);w.responseType="arraybuffer";w.overrideMimeType?w.overrideMimeType("text/plain; charset=x-user-defined"):
w.setRequestHeader("Accept-Charset","x-user-defined");w.onload=function(){200==this.status&&f(new Uint8Array(this.response))};w.send(null)})}):ff=function(){return ac()};var Vc="undefined"!==typeof Vc?Vc:{},Nh={},rd;for(rd in Vc)Vc.hasOwnProperty(rd)&&(Nh[rd]=Vc[rd]);Vc.arguments=[];Vc.thisProgram="./this.program";Vc.quit=function(e,f){throw f;};Vc.preRun=[];Vc.postRun=[];var rf=!0,hf=!1,Fe="";if(rf||hf)hf?Fe=self.location.href:document.currentScript&&(Fe=document.currentScript.src),Fe=0!==Fe.indexOf("blob:")?
Fe.substr(0,Fe.lastIndexOf("/")+1):"",Vc.read=function(e){var f=new XMLHttpRequest;f.open("GET",e,!1);f.send(null);return f.responseText},hf&&(Vc.readBinary=function(e){var f=new XMLHttpRequest;f.open("GET",e,!1);f.responseType="arraybuffer";f.send(null);return new Uint8Array(f.response)}),Vc.readAsync=function(e,f,w){var Pa=new XMLHttpRequest;Pa.open("GET",e,!0);Pa.responseType="arraybuffer";Pa.onload=function(){200==Pa.status||0==Pa.status&&Pa.response?f(Pa.response):w()};Pa.onerror=w;Pa.send(null)},
Vc.setWindowTitle=function(e){document.title=e};var We=Vc.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof e?e:null),Hg=Vc.printErr||("undefined"!==typeof e?e:"undefined"!==typeof console&&console.warn.bind(console)||We);for(rd in Nh)Nh.hasOwnProperty(rd)&&(Vc[rd]=Nh[rd]);Nh=e;var Rg={"f64-rem":function(e,f){return e%f},"debugger":function(){debugger}},Rd=0;"object"!==typeof WebAssembly&&Hg("no native wasm support detected");var wd=!1,ze="undefined"!==typeof TextDecoder?
new TextDecoder("utf8"):e;"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var lb,ic,Yd,ne=109360,zb=Vc.TOTAL_MEMORY||16777216;5242880>zb&&Hg("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+zb+"! (TOTAL_STACK=5242880)");if(Vc.buffer)var Zf=Vc.buffer;else{if("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory){var Fh=new WebAssembly.Memory({initial:zb/65536});Zf=Fh.buffer}else Zf=new ArrayBuffer(zb);Vc.buffer=Zf}Ha();Yd[ne>>2]=5352496;var Gf=[],ej=[],Tg=[],Ub=
[function(){f.AscFonts.Bzb()}],nh=!1,vb=0,sd=null,jd=null;Vc.preloadedImages={};Vc.preloadedAudios={};var Le="fonts.wasm";Qb(Le)||(Le=Oa(Le));Vc.asm=function(e,f){f.memory=Fh;f.table=new WebAssembly.Table({initial:814,maximum:814,element:"anyfunc"});f.__memory_base=1024;f.__table_base=0;return Ya(f)};ej.push({func:function(){Xc()}});var gd={},uc={CMa:[null,[],[]],xEg:function(e,f){var w=uc.CMa[e];0===f||10===f?((1===e?We:Hg)(db(w,0)),w.length=0):w.push(f)},DFc:0,get:function(){uc.DFc+=4;return Yd[uc.DFc-
4>>2]},YAg:function(){var e=uc.get();return e?db(ic,e,void 0):""},CLg:function(){var e=uc.get();uc.get();return e},HLg:function(){uc.get()}};Nh=Vc.asm({},{b:Ja,e:function(e){Rd=e},d:function(){return Rd},r:function(e,f,w){var Pa=Eg();try{return yk(e,f,w)}catch(Nd){Mg(Pa);if(Nd!==Nd+0&&"longjmp"!==Nd)throw Nd;Pc(1,0)}},q:function(e,f,w,Ja){var Pa=Eg();try{return zk(e,f,w,Ja)}catch(dj){Mg(Pa);if(dj!==dj+0&&"longjmp"!==dj)throw dj;Pc(1,0)}},p:function(e,f,w,Ja,Da){var Pa=Eg();try{return Gc(e,f,w,Ja,
Da)}catch(Bo){Mg(Pa);if(Bo!==Bo+0&&"longjmp"!==Bo)throw Bo;Pc(1,0)}},o:function(e,f,w){var Pa=Eg();try{Vk(e,f,w)}catch(Nd){Mg(Pa);if(Nd!==Nd+0&&"longjmp"!==Nd)throw Nd;Pc(1,0)}},n:function(e,f,Ja,Da,Ha){var Pa=Eg();try{w(e,f,Ja,Da,Ha)}catch(Bo){Mg(Pa);if(Bo!==Bo+0&&"longjmp"!==Bo)throw Bo;Pc(1,0)}},m:bb,l:function(){},k:function(e){Vc.___errno_location&&(Yd[Vc.___errno_location()>>2]=e);return e},A:function(f,w){uc.DFc=w;try{var Pa=uc.X9f();uc.get();var Da=uc.get(),Ha=uc.get(),Xa=uc.get();e.ZLg(Pa,
Da,Xa);Yd[Ha>>2]=Pa.position;Pa.iCg&&0===Da&&0===Xa&&(Pa.iCg=null);return 0}catch(Bo){return"undefined"!==typeof e&&Bo instanceof e.Eif||Ja(Bo),-Bo.iof}},z:function(f,w){uc.DFc=w;try{var Pa=uc.X9f(),Da=uc.get(),Ha=uc.get();return uc.rLg(Pa,Da,Ha)}catch(dj){return"undefined"!==typeof e&&dj instanceof e.Eif||Ja(dj),-dj.iof}},j:function(f,w){uc.DFc=w;try{var Pa=uc.get(),Da=uc.get(),Ha=uc.get();for(w=f=0;w<Ha;w++){for(var Xa=Yd[Da+8*w>>2],bb=Yd[Da+(8*w+4)>>2],Ra=0;Ra<bb;Ra++)uc.xEg(Pa,ic[Xa+Ra]);f+=bb}return f}catch(Zh){return"undefined"!==
typeof e&&Zh instanceof e.Eif||Ja(Zh),-Zh.iof}},f:function(e,f){uc.DFc=f;return 0},y:function(f,w){uc.DFc=w;try{var Pa=uc.YAg(),Da=uc.get(),Ha=uc.get();return e.open(Pa,Da,Ha).wLg}catch(dj){return"undefined"!==typeof e&&dj instanceof e.Eif||Ja(dj),-dj.iof}},i:function(e,f){uc.DFc=f;return 0},h:function(f,w){uc.DFc=w;try{var Pa=uc.X9f();e.close(Pa);return 0}catch(Xp){return"undefined"!==typeof e&&Xp instanceof e.Eif||Ja(Xp),-Xp.iof}},g:function(){},x:function(){return zb},w:function(e,f){me(e,f)},
v:function(e,f,w){ic.set(ic.subarray(f,f+w),e)},u:tc,t:ec,c:me,s:function(){Ja("OOM")},a:ne},Zf);Vc.asm=Nh;Vc._ASC_FT_Free=function(){return Vc.asm.B.apply(null,arguments)};Vc._ASC_FT_GetFaceInfo=function(){return Vc.asm.C.apply(null,arguments)};Vc._ASC_FT_GetFaceMaxAdvanceX=function(){return Vc.asm.D.apply(null,arguments)};Vc._ASC_FT_GetKerningX=function(){return Vc.asm.E.apply(null,arguments)};Vc._ASC_FT_Get_Glyph_Measure_Params=function(){return Vc.asm.F.apply(null,arguments)};Vc._ASC_FT_Get_Glyph_Render_Buffer=
function(){return Vc.asm.G.apply(null,arguments)};Vc._ASC_FT_Get_Glyph_Render_Params=function(){return Vc.asm.H.apply(null,arguments)};Vc._ASC_FT_Glyph_Get_CBox=function(){return Vc.asm.I.apply(null,arguments)};Vc._ASC_FT_Init=function(){return Vc.asm.J.apply(null,arguments)};Vc._ASC_FT_Malloc=function(){return Vc.asm.K.apply(null,arguments)};Vc._ASC_FT_Open_Face=function(){return Vc.asm.L.apply(null,arguments)};Vc._ASC_FT_SetCMapForCharCode=function(){return Vc.asm.M.apply(null,arguments)};Vc._ASC_FT_Set_Transform=
function(){return Vc.asm.N.apply(null,arguments)};Vc._ASC_FT_Set_TrueType_HintProp=function(){return Vc.asm.O.apply(null,arguments)};Vc._FT_Done_Face=function(){return Vc.asm.P.apply(null,arguments)};Vc._FT_Done_FreeType=function(){return Vc.asm.Q.apply(null,arguments)};Vc._FT_Get_Glyph=function(){return Vc.asm.R.apply(null,arguments)};Vc._FT_Load_Glyph=function(){return Vc.asm.S.apply(null,arguments)};Vc._FT_Set_Char_Size=function(){return Vc.asm.T.apply(null,arguments)};Vc._FT_Set_Transform=function(){return Vc.asm.U.apply(null,
arguments)};var Xc=Vc.___emscripten_environ_constructor=function(){return Vc.asm.V.apply(null,arguments)},Zc=Vc._free=function(){return Vc.asm.W.apply(null,arguments)},re=Vc._malloc=function(){return Vc.asm.X.apply(null,arguments)},Pc=Vc._setThrew=function(){return Vc.asm.Y.apply(null,arguments)},Mg=Vc.stackRestore=function(){return Vc.asm.da.apply(null,arguments)},Eg=Vc.stackSave=function(){return Vc.asm.ea.apply(null,arguments)},yk=Vc.dynCall_iii=function(){return Vc.asm.Z.apply(null,arguments)},
zk=Vc.dynCall_iiii=function(){return Vc.asm._.apply(null,arguments)},Gc=Vc.dynCall_iiiii=function(){return Vc.asm.$.apply(null,arguments)};Vc.dynCall_vi=function(){return Vc.asm.aa.apply(null,arguments)};var Vk=Vc.dynCall_vii=function(){return Vc.asm.ba.apply(null,arguments)},w=Vc.dynCall_viiii=function(){return Vc.asm.ca.apply(null,arguments)};Vc.asm=Nh;xc.prototype=Error();xc.prototype.constructor=xc;jd=function pl(){Vc.calledRun||nc();Vc.calledRun||(jd=pl)};Vc.run=nc;Vc.abort=Ja;if(Vc.preInit)for("function"==
typeof Vc.preInit&&(Vc.preInit=[Vc.preInit]);0<Vc.preInit.length;)Vc.preInit.pop()();Vc.noExitRuntime=!0;nc();f.AscFonts=f.AscFonts||{};kd=f.AscFonts;kd.Hig=function(){return Vc._ASC_FT_Init()};kd.rmg=35;kd.rKg=38;kd.smg=40;kd.Djg=function(e,f){Vc._ASC_FT_Set_TrueType_HintProp(e,f)};kd.Iig=function(e){var f=Vc._ASC_FT_Malloc(e.size);Vc.HEAP8.set(e.data,f);return{Tug:!0,data:f,Rh:e.size}};kd.VHd=function(e){var f=kd.i0b[e];f&&!0!==f.Tug&&(f=kd.Iig(kd.i0b[e]),kd.i0b[e]=null,kd.i0b[e]=f)};Xa.prototype.load=
function(e){if(e=Vc._ASC_FT_GetFaceInfo(e)){var f=new Int32Array(Vc.HEAP8.buffer,e,Math.min(Vc.HEAP8.length-e>>2,250)),w=0;this.tNa=Math.abs(f[w++]);this.B3=f[w++];this.TX=f[w++];this.height=f[w++];this.mY=f[w++];this.vwc=f[w++];this.fK=f[w++];this.iYb=f[w++];this.pFc=f[w++];this.yNd=f[w++];for(var Ja=f[w++];Ja;)this.P2+=String.fromCharCode(Ja),Ja=f[w++];for(Ja=f[w++];Ja;)this.PAa+=String.fromCharCode(Ja),Ja=f[w++];this.Ksf=f[w++];this.beg=f[w++];this.Xdg=f[w++];this.VQf=f[w++];this.WQf=f[w++];this.aeg=
f[w++];this.TQf=f[w++];this.UQf=f[w++];this.Zdg=f[w++];w++;this.$dg=kd.MY.hQ(f[w++]);w++;w++;w++;w++;this.Ydg=f[w++];this.x$f=f[w++];this.w$f=f[w++];Ja=f[w++];for(var Da=0;Da<Ja;Da++)this.esf.push(f[w++]);Vc._ASC_FT_Free(e)}};kd.Jhg=Xa;kd.XIg=mf;kd.WIg=ub;kd.hyf=function(e,f,w){return Vc._ASC_FT_Open_Face(e,f.data,f.Rh,w)};kd.sjg=function(e,f,w){e=Vc._ASC_FT_Get_Glyph_Measure_Params(e,f?1:0);if(!e)return null;var Ja=15;f&&(Ja=Vc.HEAP32[e>>2]);var Da=new Int32Array(Vc.HEAP8.buffer,e,4*Ja),Ha=new mf;
Ha.W5f=Da[1];Ha.Y5f=Da[2];Ha.V5f=Da[3];Ha.X5f=Da[4];Ha.width=Da[5];Ha.height=Da[6];Ha.Mia=Da[7];Ha.Era=Da[8];Ha.goa=Da[9];Ha.iia=Da[10];Ha.mCa=Da[11];Ha.YAa=Da[12];Ha.dvc=Da[13];Ha.AEc=Da[14];if(f){w.start(f);for(var Xa=15;Xa<Ja;)switch(Da[Xa++]){case 0:w.W2f(Da[Xa++],Da[Xa++],f);break;case 1:w.N2f(Da[Xa++],Da[Xa++],f);break;case 2:w.h2f(Da[Xa++],Da[Xa++],Da[Xa++],Da[Xa++],f);break;case 3:w.j2f(Da[Xa++],Da[Xa++],Da[Xa++],Da[Xa++],Da[Xa++],Da[Xa++],f)}w.end(f)}Vc._ASC_FT_Free(e);return Ha};kd.lZf=
function(e,f){e=Vc._ASC_FT_Get_Glyph_Render_Params(e,f);if(!e)return null;f=new Int32Array(Vc.HEAP8.buffer,e,24);var w=new ub;w.left=f[0];w.top=f[1];w.width=f[2];w.rows=f[3];w.pitch=f[4];w.mode=f[5];Vc._ASC_FT_Free(e);return w};kd.j3d=Vc._FT_Load_Glyph;kd.iyf=Vc._ASC_FT_Set_Transform;kd.k3d=Vc._FT_Set_Char_Size;kd.Iif=Vc._ASC_FT_SetCMapForCharCode;kd.njg=Vc._ASC_FT_GetKerningX;kd.mjg=Vc._ASC_FT_GetFaceMaxAdvanceX;kd.kZf=function(e,f,w){e=Vc._ASC_FT_Get_Glyph_Render_Buffer(e);e=new Uint8Array(Vc.HEAP8.buffer,
e,f.pitch*f.rows);if(!w)return e;kd.iTb.cL(f.width,f.rows);w=0;var Ja=kd.iTb.mVa.data;if(f.pitch>=f.width)for(var Da=0;Da<f.rows;++Da,w+=f.pitch){var Ha=3+Da*kd.iTb.pitch;for(var Xa=0;Xa<f.width;Xa++,Ha+=4)Ja[Ha]=e[w+Xa]}else{var bb,Ra;for(Da=0;Da<f.rows;++Da,w+=f.pitch)for(Ha=3+Da*kd.iTb.pitch,Xa=Ra=bb=0;Xa<f.width;Xa++,Ha+=4,bb++)8==bb&&(bb=0,Ra++),Ja[Ha]=e[w+Ra]&1<<7-bb?255:0}};kd.Bzb()})(window,void 0);"use strict";
(function(f,e){function Oa(){this.ad=this.lw=null;this.B=this.G=this.R=0;this.wbb=this.qta=null}function eb(){this.Ura=this.Uia=this.KEc=this.ZYa=0;this.MR=new Oa}function db(){this.ega=this.aTa=this.z_a=this.NMa=0;this.V_a=null}function Za(){this.sgd=this.ugd=this.tgd=this.IDc=this.rgd=this.qgd=this.SKb=this.xeb=0}function Ha(){this.qWf;this.c$;this.vQf;this.sMc;this.ala;this.px=new db;this.$ca=new Za;this.GBa=!1;this.Ay=null}function Da(){this.qa=this.pa=0;this.qib=25.4/72;this.rib=25.4/72;this.Dxb=
!1;this.eOa=this.bG=this.$hc=this.shift=0}function Qb(){this.wVb={};this.Yzf=function(f,Da,Ha,bb,Ja,Xa,Oa){var Ya=f.Vv,nc=Ra.Kt.PBa(Da);if(e===nc||""==nc)return null;var Za=this.wVb[nc];if(!Za){Za=Ra.lTa[Ra.z6a[nc]];var db=Ra.B1a.uCa;f.Gzf()&&(db|=Ra.B1a.lia);f.Kzf()&&(db|=Ra.B1a.mia);Za=Za.OG(ac.eR,Ya,f.ozb,db,f.tzb,f.$Xb,e,!0);if(!Za)return null;Za.DHd();this.wVb[nc]=Za}if(!Za)return null;Za.oKd(f.ozb,f.tzb,f.$Xb);f=f.RXb;Ya=Za.RXb;Ya[0]=f[0];Ya[1]=f[1];Ya[2]=f[2];Ya[3]=f[3];Ya[4]=f[4];Ya[5]=f[5];
Za.ybb();return Za.gVb(Da,Ha,bb,Ja,Xa,Oa,!0)};this.cdb=function(){if(!this.w3d){this.w3d=!0;for(var e in this.wVb)this.wVb[e].cdb();delete this.w3d}};this.dZb=function(){if(!this.v3d){this.v3d=!0;for(var e in this.wVb)this.wVb[e].dZb();delete this.v3d}}}var Ra=f.AscFonts,ac=f.AscCommon;Ra.XSc={mZf:0,wJg:1,ujg:2,yJg:4,tjg:8,EJg:16,rJg:32,qJg:64,xJg:128,sJg:512,vJg:1024,tJg:2048,uJg:4096,nZf:8192,oZf:32768,oJg:1048576,pJg:2097152,nJg:4194304};Ra.nId={pZf:0,Bjg:1,Cjg:2,zjg:3,Ajg:4,GJg:5};Ra.FJg={DJg:(Ra.nId.pZf&
15)<<16,BJg:(Ra.nId.Bjg&15)<<16,CJg:(Ra.nId.Cjg&15)<<16,zJg:(Ra.nId.zjg&15)<<16,AJg:(Ra.nId.Ajg&15)<<16};Ra.Tzf=Ra.XSc.mZf|Ra.XSc.ujg|Ra.XSc.nZf|Ra.XSc.oZf;Ra.Akg=Ra.XSc.mZf|Ra.XSc.nZf|Ra.XSc.oZf;Ra.UCg=function(e){Ra.Web||(Ra.Web=[],Ra.Web.push(4352),Ra.Web.push(4607),Ra.Web.push(11904),Ra.Web.push(40959),Ra.Web.push(44032),Ra.Web.push(55215),Ra.Web.push(63744),Ra.Web.push(64255),Ra.Web.push(65280),Ra.Web.push(65519),Ra.Web.push(131072),Ra.Web.push(173791),Ra.Web.push(194560),Ra.Web.push(195103));
if(e<Ra.Web[0])return!1;for(var f=Ra.Web,Da=Ra.Web.length,Ha=0;Ha<Da;Ha+=2)if(e>=f[Ha]&&e<=f[Ha+1])return!0;return!1};var Ya=Ra.iTb;Ra.oOf=function(){};var bb=Ra.nId.pZf,me={MYa:0,Yjc:1,sXb:2};Oa.prototype={zIf:function(e,f,Da,Ha,Ja){if(e!=this.R||f!=this.G||Da!=this.B)this.R=e,this.G=f,this.B=Da,null!=this.lw?(this.ad.fillStyle=255==this.R&&255==this.G&&255==this.B?"rgb(255,255,254)":"rgb("+this.R+","+this.G+","+this.B+")",this.ad.fillRect(0,0,Ha,Ja)):(e=this.qta,e.Jva.bMa.fillStyle=255==this.R&&
255==this.G&&255==this.B?"rgb(255,255,254)":"rgb("+this.R+","+this.G+","+this.B+")",this.qta.Jva.bMa.fillRect(e.zc.Oc*e.Va,e.zc.qa,Ha,Ja))},AIf:function(e,f,Da,Ha,Ja){if(e!=this.R||f!=this.G||Da!=this.B)this.R=e,this.G=f,this.B=Da,null!=this.lw?(this.ad.fillStyle="rgb("+this.R+","+this.G+","+this.B+")",this.ad.fillRect(0,0,Ha,Ja)):(e=this.qta,e.Jva.bMa.fillStyle="rgb("+this.R+","+this.G+","+this.B+")",this.qta.Jva.bMa.fillRect(e.zc.Oc*e.Va,e.zc.qa,Ha,Ja))},oDc:e,we:function(e,f){0!=e&&0!=f&&(this.lw=
document.createElement("canvas"),this.lw.width=0==e?1:e,this.lw.height=0==f?1:f,this.ad=this.lw.getContext("2d"),this.ad.globalCompositeOperation="source-in")}};Oa.prototype.oDc=ac.sf.Kqb&&ac.sf.sEc?Oa.prototype.zIf:Oa.prototype.AIf;eb.prototype={xLf:function(e){var f;var Da=!1;Math.max(this.Uia,this.Ura)>(null==e.ZXa?0:e.ZXa.qub)/10&&(Da=!0);var Ha=f=0;Da?(this.MR.we(this.Uia,this.Ura),e=this.MR.ad):(this.MR.qta=e.ZXa.QM(this.Uia,this.Ura),e=this.MR.qta.Jva.bMa,f=this.MR.qta.zc.Oc*this.MR.qta.Va,
Ha=this.MR.qta.zc.qa);0<this.Uia&&0<this.Ura&&e.putImageData(Ya.mVa,f,Ha,0,0,this.Uia,this.Ura);if(null!=Ya.mVa){var Ja=3;Da=4*(Ya.width-this.Uia);e=Ya.mVa.data;for(Ha=0;Ha<this.Ura;Ha++){for(f=0;f<this.Uia;f++)e[Ja]=0,Ja+=4;Ja+=Da}}},Gd:function(e,f,Da){var Ha=this.Uia,Ja=this.Ura;if(null!=this.MR.wbb)e.drawImage(this.MR.wbb,0,0,Ha,Ja,f,Da,Ha,Ja),this.MR.wbb=null;else if(null!=this.MR.lw)e.drawImage(this.MR.lw,0,0,Ha,Ja,f,Da,Ha,Ja);else{var Xa=this.MR.qta;e.drawImage(Xa.Jva.p$,Xa.zc.Oc*Xa.Va,Xa.zc.qa,
Ha,Ja,f,Da,Ha,Ja)}},Znf:function(e,f,Da,Ha,Ja,Xa){if(null!=this.MR.wbb)e.drawImage(this.MR.wbb,Xa,0,Ha,Ja,f,Da,Ha,Ja),this.MR.wbb=null;else if(null!=this.MR.lw)e.drawImage(this.MR.lw,Xa,0,Ha,Ja,f,Da,Ha,Ja);else{var bb=this.MR.qta;e.drawImage(bb.Jva.p$,bb.zc.Oc*bb.Va+Xa,bb.zc.qa,Ha,Ja,f,Da,Ha,Ja)}},$nf:function(e,f,Da,Ha){var Ja=f,Xa=Da;f+=this.Uia;var bb=Da+this.Ura,Ra=Da=0,Oa=this.Uia,Ya=this.Ura;Ja<Ha.ee&&(Da=Ha.ee-Ja,Ja+=Da,Oa-=Da);Xa<Ha.t&&(Ra=Ha.t-Xa,Xa+=Ra,Ya-=Ra);f>Ha.r&&(Oa-=f-Ha.r);bb>Ha.ob&&
(Ya-=bb-Ha.ob);0>=Oa||0>=Ya||(null!=this.MR.wbb?(e.drawImage(this.MR.wbb,Da,Ra,Oa,Ya,Ja,Xa,Oa,Ya),this.MR.wbb=null):null!=this.MR.lw?e.drawImage(this.MR.lw,Da,Ra,Oa,Ya,Ja,Xa,Oa,Ya):(Ha=this.MR.qta,e.drawImage(Ha.Jva.p$,Ha.zc.Oc*Ha.Va+Da,Ha.zc.qa+Ra,Oa,Ya,Ja,Xa,Oa,Ya)))},Cub:function(){null!=this.MR.qta&&this.MR.qta.Jva.Cub(this.MR.qta)}};Da.prototype={start:function(){},W2f:function(e,f,Da){this.Dxb&&(Da.Ow(),this.Dxb=!1);this.bG=this.pa+e/64*this.qib;this.eOa=this.qa-f/64*this.rib;Da.sj(this.bG,
this.eOa);return 0},pQf:function(e,f){return this.W2f(e.x,e.y,f)},N2f:function(e,f,Da){this.bG=this.pa+e/64*this.qib;this.eOa=this.qa-f/64*this.rib;Da.Ac(this.bG,this.eOa);this.Dxb=!0;return 0},Erf:function(e,f){return this.N2f(e.x,e.y,f)},h2f:function(e,f,Da,Ha,Ja){e=this.pa+e/64*this.qib;f=this.qa-f/64*this.rib;Da=this.pa+Da/64*this.qib;Ha=this.qa-Ha/64*this.rib;Ja.Td(1/3*(this.bG+2*e),1/3*(this.eOa+2*f),1/3*(2*e+Da),1/3*(2*f+Ha),Da,Ha);this.bG=Da;this.eOa=Ha;this.Dxb=!0;return 0},qTe:function(e,
f,Da){return this.h2f(e.x,e.y,f.x,f.y,Da)},j2f:function(e,f,Da,Ha,Ja,Xa,bb){this.bG=this.pa+Ja/64*this.qib;this.eOa=this.qa-Xa/64*this.rib;bb.Td(this.pa+e/64*this.qib,this.qa-f/64*this.rib,this.pa+Da/64*this.qib,this.qa-Ha/64*this.rib,this.bG,this.eOa);this.Dxb=!0;return 0},Jnf:function(e,f,Da,Ha){return this.j2f(e.x,e.y,f.x,f.y,Da.x,Da.y,Ha)},end:function(e){this.Dxb&&(e.Ow(),this.Dxb=!1)}};f.AscFonts.Bub=me;f.AscFonts.Kvf=function(){this.aTd="undefined"==typeof Float64Array?Array(6):new Float64Array(6);
this.RXb="undefined"==typeof Float64Array?Array(6):new Float64Array(6);this.FPf=!0;this.SKc=!1;this.ozb=1;this.$Xb=this.tzb=0;this.Q0b=this.RKc=!1;this.mcb=0;this.VXb=new Ra.Chf;this.OEd=0;this.Cza=this.Y2=null;this.i5e=1;this.pnd=this.ond=-1;this.Qra=!1;this.Tia=this.Gla=this.iva=this.Lta=this.cTd=0;this.PXb=[];this.QXb=[];this.Vv=null;this.lzb=this.b8d=this.D6b=!0;this.H8f=e;this.UVb=new Qb;this.fyf=function(e,f,Da){Da=Ra.j3d(e,f,Da);if(0!=Da&&this.D6b){e=Ra.j3d(e,f,Ra.Tzf);if(0!=e)return Da;this.D6b=
!1;return e}return Da};this.ble=function(){var e=this.aTd;this.RKc?(e[0]=1,e[1]=0,e[2]=.3090169943749):(e[0]=1,e[1]=0,e[2]=0);e[3]=1;e[4]=0;e[5]=0;this.ybb()};this.iBf=function(){var e=this.RXb;e[0]=1;e[1]=0;e[2]=0;e[3]=1;e[4]=0;e[5]=0;this.C_d()};this.C_d=function(){this.lzb=!0;var e=this.RXb;1==e[0]&&0==e[1]&&0==e[2]&&1==e[3]&&(this.lzb=!1,this.ybb())};this.ybb=function(){var e=this.aTd,f=this.RXb;Ra.iyf(this.Y2,65536*(e[0]*f[0]+e[1]*f[2])>>0,65536*(e[0]*f[1]+e[1]*f[3])>>0,65536*(e[2]*f[0]+e[3]*
f[2])>>0,65536*(e[2]*f[1]+e[3]*f[3])>>0)};this.oKd=function(e,f,Da){f=f+.5>>0;Da=Da+.5>>0;var Ha=e/this.ozb;if((Ha=1.001<Ha||.999>Ha?!0:!1)||f!=this.tzb||Da!=this.$Xb)this.tzb=f,this.$Xb=Da,Ha&&(this.ozb=e,this.ybb()),this.i5e=this.tzb/72*this.ozb,this.OEd=Ra.k3d(this.Y2,0,64*e>>0,f,Da),this.cdb()};this.cdb=function(){this.nZb();this.dZb();this.UVb&&this.UVb.cdb()};this.dZb=function(){this.PXb=[];this.QXb=[];this.UVb&&this.UVb.dZb()};this.nZb=function(){if(null!=this.Vv&&null!=this.Vv.ZXa){var e=
this.PXb,f;for(f in e)null!=e[f].Ay&&e[f].Ay.Cub();e=this.QXb;for(f in e)null!=e[f].Ay&&e[f].Ay.Cub()}};this.dYa=function(e,f,Da,Ha,Ja,Xa){var bb=this.RXb,Ra=bb[0]==e&&bb[1]==-f&&bb[2]==-Da&&bb[3]==Ha;if(Ra&&bb[4]==Ja&&bb[5]==Xa)return!1;bb[0]=e;bb[1]=-f;bb[2]=-Da;bb[3]=Ha;bb[4]=Ja;bb[5]=Xa;Ra||this.cdb();this.C_d();return!0};this.Sif=function(e){var f=Ra.Iif(this.Y2,e);if(0<f)return f;-1!=this.pnd&&61440>e&&(f=Ra.Iif(this.Y2,e+61440));return f};this.gVb=function(f,Oa,Za,nc,Ja,Xa,db){var ac=new Ha;
ac.qWf=f;var kd=this.Qra?f:Ra.Iif(this.Y2,f);0>=kd&&!this.Qra&&-1!=this.pnd&&61440>f&&(kd=Ra.Iif(this.Y2,f+61440));if(0>=kd){if(!0===db)return null;if(!this.Qra&&this.UVb&&(kd=this.UVb.Yzf(this,f,Oa,Za,nc,Ja,Xa)))return kd;if(0<=this.ond)kd=this.ond,ac.c$=me.Yjc;else return ac.c$=me.sXb,ac.sMc=-1,ac.ala=(Ra.mjg(this.Y2)>>6)/2,ac}else ac.c$=me.MYa;ac.sMc=kd;ac.vQf=0;var mf=this.Fyf();if(this.Qra||!Oa||this.Q0b||!Ra.UCg(f))mf|=Ra.XSc.tjg;if(this.fyf(this.Y2,kd,mf))return ac;f=null;e!==nc&&(f=new Da,
f.qib=25.4/this.tzb,f.rib=25.4/this.$Xb,Ja!==e&&(f.pa=Ja),Xa!==e&&(f.qa=Xa));Ja=Ra.sjg(this.Y2,nc,f);if(null==Ja||e!==nc)return ac;nc=65535!=this.Cza.Ksf&&800<=this.Cza.beg?!0:!1;ac.ala=Ja.dvc*this.i5e/this.Tia;this.Q0b&&this.Vv.qjf&&!nc&&(ac.ala+=1);ac.px.NMa=Ja.W5f>>6;ac.px.z_a=Ja.V5f>>6;ac.px.aTa=Ja.Y5f>>6;ac.px.ega=Ja.X5f>>6;Xa=ac.$ca;Xa.xeb=Ja.width>>6;Xa.SKb=Ja.height>>6;Xa.qgd=Ja.Era>>6;Xa.rgd=Ja.goa>>6;Xa.IDc=Ja.Mia>>6;Xa.tgd=Ja.mCa>>6;Xa.ugd=Ja.YAa>>6;Xa.sgd=Ja.iia>>6;if(db&&0==Xa.IDc&&0==
Ja.width)return null;if(!Oa){if(Za&&(Oa=Ra.lZf(this.Y2,bb))){nc=Ra.kZf(this.Y2,Oa,!1);Oa=ac.px;f=nc.data;Za=nc.width;db=nc.rows;kd=nc.pitch;nc={AJc:0,BJc:0,vKf:0,uKf:0};mf=!1;for(Ja=0;Ja<Za;Ja++){var tc=4*Ja+3;for(Xa=0;Xa<db;Xa++,tc+=kd)if(0!=f[tc]){mf=!0;break}if(mf)break;nc.AJc++}mf=!1;for(Ja=Za-1;0<=Ja;Ja--){tc=4*Ja+3;for(Xa=0;Xa<db;Xa++,tc+=kd)if(0!=f[tc]){mf=!0;break}if(mf)break;nc.vKf++}mf=!1;for(Xa=0;Xa<db;Xa++){tc=Xa*kd+3;for(Ja=0;Ja<Za;Ja++,tc+=4)if(0!=f[tc]){mf=!0;break}if(mf)break;nc.BJc++}mf=
!1;for(Xa=db-1;0<=Xa;Xa--){tc=Xa*kd+3;for(Ja=0;Ja<Za;Ja++,tc+=4)if(0!=f[tc]){mf=!0;break}if(mf)break;nc.uKf++}if(null!=Ya.mVa)for(f=3,kd=4*(Ya.width-Za),mf=Ya.mVa.data,Xa=0;Xa<db;Xa++){for(Ja=0;Ja<Za;Ja++)mf[f]=0,f+=4;f+=kd}Oa.V_a=nc}return ac}ac.GBa=!0;Oa=Ra.lZf(this.Y2,bb);if(!Oa||0==Oa.pitch)return ac;ac.Ay=new eb;ac.Ay.ZYa=Oa.left;ac.Ay.KEc=Oa.top;ac.Ay.Uia=Oa.width;ac.Ay.Ura=Oa.rows;Ra.kZf(this.Y2,Oa,!0);if(this.Q0b&&this.FPf&&!nc)for(ac.Ay.Uia++,Oa=ac.Ay.Uia,Za=ac.Ay.Ura,Xa=Ya.mVa.data,Ja=db=
0;db<Za;++db,Ja+=Ya.pitch)for(nc=Oa-1;0<=nc;--nc)0!=nc&&(f=Ja+4*nc+3,Xa[f]=Oa-1==nc?Xa[f-4]:Math.min(255,Xa[f-4]+Xa[f]));ac.Ay.xLf(this.Vv);return ac};this.Zab=function(f){if(0>=f.XF)return!0;var Da=0,Ha=0;this.lzb&&this.ybb();for(var bb=!1===this.Qra?this.PXb:this.QXb,Ja=0;Ja<f.XF;++Ja){var Xa=f.tCb(Ja).CLa,Ra=bb[Xa];e==Ra&&(bb[Xa]=this.gVb(Xa,!1),Ra=bb[Xa]);Xa=Ra.sMc;var Oa=Ra.c$;me.sXb==Oa?(f.oCc(Ja,Ha,0),f.iCc(Ja,0,0,0,0),f.VFb(Ja,me.sXb),Ha+=Ra.ala+this.mcb,Da=0):(me.Yjc==Oa?f.VFb(Ja,me.Yjc):
f.VFb(Ja,me.MYa),this.SKc&&Da&&0<Ja&&f.tCb(Ja).c$==f.tCb(Ja-1).c$&&(Ha+=this.R5b(Da,Xa)),Da=f.oX+Ha,Oa=f.pX+0,f.oCc(Ja,f.Wca[4]+Da*f.Wca[0]+Oa*f.Wca[2]-f.oX,f.Wca[5]+Da*f.Wca[1]+Oa*f.Wca[3]-f.pX),Da=Ra.$ca,f.skf(Ja,Da.xeb,Da.SKb,Da.IDc,Da.qgd,Da.rgd,Da.sgd,Da.tgd,Da.ugd),f.iCc(Ja,Ra.px.NMa,Ra.px.ega,Ra.px.z_a,Ra.px.aTa),Ha+=Ra.ala+this.mcb,Da=Xa)}f.qrb=Ha+f.oX;f.FRb=0+f.pX};this.dc=function(f){if(0>=f.XF)return!0;this.lzb&&this.ybb();for(var Da=0,Ha=0,bb=!1===this.Qra?this.PXb:this.QXb,Ja=0;Ja<f.XF;++Ja){var Xa=
f.tCb(Ja),Ra=Xa.CLa,Oa=bb[Ra];if(e==Oa||null==Oa.Ay)bb[Ra]=this.gVb(Ra,!0),Oa=bb[Ra];Ra=Oa.sMc;var Ya=Oa.c$;me.sXb==Ya?(f.oCc(Ja,Ha,0),f.iCc(Ja,0,0,0,0),f.VFb(Ja,me.sXb),Ha+=Oa.ala+this.mcb,Da=0):(me.Yjc==Ya?f.VFb(Ja,me.Yjc):f.VFb(Ja,me.MYa),this.SKc&&Da&&0<Ja&&f.tCb(Ja).c$==f.tCb(Ja-1).c$&&(Ha+=this.R5b(Da,Ra)),Da=f.oX+Ha,Ya=f.pX+0,f.oCc(Ja,f.Wca[4]+Da*f.Wca[0]+Ya*f.Wca[2]-f.oX,f.Wca[5]+Da*f.Wca[1]+Ya*f.Wca[3]-f.pX),Xa.$ca=Oa.$ca,f.iCc(Ja,Oa.px.NMa,Oa.px.ega,Oa.px.z_a,Oa.px.aTa),Ha+=Oa.ala+this.mcb,
Xa.GBa=Oa.GBa,Xa.Ay=Oa.Ay,Da=Ra)}f.qrb=Ha+f.oX;f.FRb=0+f.pX};this.Pxd=function(f){this.lzb&&this.ybb();var Da=f.NJ[0],Ha=Da.CLa,bb=!1===this.Qra?this.PXb:this.QXb,Ja=bb[Ha];if(e==Ja||null==Ja.Ay&&!1===Ja.GBa)bb[Ha]=this.gVb(Ha,!0),Ja=bb[Ha];if(Ja)if(Ha=Ja.c$,Da.c$=Ja.c$,me.sXb==Ha)Da.fy=0,Da.hx=0,Da.iDa=0,Da.Pua=0,Da.OMa=0,Da.hDa=0;else{Ha=f.oX;bb=f.pX;var Xa=f.Wca;Da.fy=Xa[4]+Ha*Xa[0]+bb*Xa[2]-f.oX;Da.hx=Xa[5]+Ha*Xa[1]+bb*Xa[3]-f.pX;Da.$ca=Ja.$ca;Da.GBa=Ja.GBa;Da.Ay=Ja.Ay;f.qrb=Ja.ala+this.mcb+f.oX;
f.FRb=f.pX}};this.NY=function(f,Da){this.lzb&&this.ybb();var Ha=!1===this.Qra?this.PXb:this.QXb,bb=Ha[f];e==bb&&(Ha[f]=this.gVb(f,!1,Da),bb=Ha[f]);return bb};this.Gyf=function(e,f,Da,Ha){this.lzb&&this.ybb();this.gVb(e,!1,!1,f,Da,Ha)};this.Vif=function(e,f){var Da=e.XF;if(!(0>=Da))for(var Ha=0;Ha<Da;++Ha){var Ja=e.NJ[Ha],Xa=e.oX+25.4*Ja.fy/this.tzb,bb=e.pX+25.4*Ja.hx/this.$Xb;f.pj();this.Gyf(Ja.CLa,f,Xa,bb);f.Vs();f.Ct()}};this.Fyf=function(){return this.D6b&&this.b8d?this.Vv.pJd:Ra.Tzf};this.R5b=
function(e,f){return Ra.njg(this.Y2,e,f)>>6};this.rBa=function(e){this.Qra!=e&&(this.Qra=e)};this.qkf=function(e){this.mcb=e};this.Gzf=function(){return this.Q0b?!0:-1!=this.Cza.PAa.indexOf("Bold")?!0:!1};this.Kzf=function(){return this.RKc?!0:-1!=this.Cza.PAa.indexOf("Italic")?!0:!1};this.ukf=function(e){this.RKc!=e&&(this.cdb(),this.RKc=e,this.ble())};this.tkf=function(e){this.Q0b!=e&&(this.cdb(),this.Q0b=e)};this.jJd=function(){return 0==this.OEd};this.I1a=function(){return this.Lta};this.zOa=
function(){return this.iva};this.MF=function(){return this.Gla};this.DHd=function(){this.b8d=this.D6b=!0};this.L6f=function(){var e=this.Cza,f=[];f.push(e.tNa);65535!=e.Ksf?(f.push(e.VQf),f.push(-e.WQf)):(f.push(e.w$f),f.push(e.x$f));return f};this.Wlg=function(e,f){this.Y2=e;this.Cza=new Ra.Jhg;this.Cza.load(this.Y2);this.Tia=this.Cza.tNa;this.Lta=this.Cza.B3;this.iva=this.Cza.TX;this.Gla=this.Cza.height;if(f.vjf&&65535!=this.Cza.Ksf)if(f.Zxd){var Da=this.Cza.VQf,Ha=-this.Cza.WQf;if(0!=(this.Cza.$dg&
770703360)){var Ja=.3*(Da-Ha)>>0;Da+=Ja+1>>1;Ha-=Ja>>1}this.Cza.height<Da-Ha&&(this.Lta=Da,this.iva=Ha,this.Gla=Da-Ha)}else 128==(this.Cza.Xdg&128)&&(this.Lta=this.Cza.TQf,this.iva=this.Cza.UQf,this.Gla=this.Cza.TQf-this.Cza.UQf+this.Cza.Zdg);this.cTd=this.Cza.iYb;this.ond=this.Cza.aeg;this.pnd=this.Cza.Ydg;this.OEd=Ra.k3d(e,0,64*this.ozb,0,0);this.iBf();this.ble();!0===f.SKc&&(this.SKc=0!=(this.Cza.mY&64)?!0:!1);if(0!=this.Cza.esf.length)for(this.H8f=[],e=this.Cza.esf.length-1;0<=e;e--)this.H8f[this.Cza.esf[e]>>
6]=!0}};f.AscFonts.Bzb()})(window);"use strict";(function(f){function e(){this.eK=Oa.Hig();this.Eza=null;this.Jsf=function(e,f){e=Oa.hyf(this.eK,e,f);if(!e)return null;f=new Oa.Kvf;f.Wlg(e,this.Eza);return f.jJd()?f:null};this.EUd=function(e,f){f=e&&f?Oa.smg:Oa.rmg;this.Eza.pJd=e?Oa.Akg:Oa.Tzf;Oa.Djg(this.eK,f)}}var Oa=f.AscFonts;f.AscFonts.gof=function(f){var db=new e;db.Eza=f;db.EUd(f.NAd,f.OAd);f.fvb=db;Oa.oOf()};f.AscFonts.Czg=function(){};f.AscFonts.Bzb()})(window);
